# Generated by Django 2.0 on 2017-12-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iota_auth', '0002_auto_20171225_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=128, verbose_name='address'),
        ),
    ]
